name: Development build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Extract project details
        id: project_details
        run: |
          echo "PROJECT_NAME=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: |
          mvn -B clean package --file pom.xml

      - name: Move Artifacts to Common Directory
        run: |
          mv target/${{ steps.project_details.outputs.PROJECT_NAME }}-${{ steps.project_details.outputs.PROJECT_VERSION }}.jar ${{ github.workspace }}/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.project_details.outputs.PROJECT_NAME }}-b${{ github.run_number }}
          path: ${{ github.workspace }}/*.jar